import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bitan Basak
 */
public class addEmployee extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rset = null;
    PreparedStatement stmt = null;
    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        con = connect.connect_db();
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        AddEmployee_empName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AddEmployee_radioMale = new javax.swing.JRadioButton();
        AddEmployee_radioFemale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        AddEmployee_position = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        AddEmployee_department = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        AddEmployee_salary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        AddEmployee_loginPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        AddEmployee_confirmPassword = new javax.swing.JPasswordField();
        AddEmployee_age = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AddEmployee_contactNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AddEmployee_email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");
        setResizable(false);

        jLabel1.setText("Employee Name:");

        jLabel2.setText("Gender:");

        buttonGroup1.add(AddEmployee_radioMale);
        AddEmployee_radioMale.setText("Male");

        buttonGroup1.add(AddEmployee_radioFemale);
        AddEmployee_radioFemale.setText("Female");

        jLabel3.setText("Position");

        AddEmployee_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Position", "Manager", "Employee"}));

        jLabel4.setText("Department:");

        AddEmployee_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "General", "Finance", "HRD", "IT"}));

        jLabel5.setText("Salary:");

        jLabel6.setText("Age:");

        jButton1.setText("Add Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Login Password:");

        jLabel8.setText("Confirm Password:");

        jLabel9.setText("Contact No:");

        jLabel10.setText("Email ID:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Contact Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddEmployee_loginPassword)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddEmployee_radioMale)
                                .addGap(18, 18, 18)
                                .addComponent(AddEmployee_radioFemale))
                            .addComponent(AddEmployee_empName)
                            .addComponent(AddEmployee_department, 0, 222, Short.MAX_VALUE)
                            .addComponent(AddEmployee_position, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddEmployee_salary, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddEmployee_age)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AddEmployee_confirmPassword)
                                .addComponent(AddEmployee_contactNo)
                                .addComponent(AddEmployee_email)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AddEmployee_empName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AddEmployee_radioMale)
                    .addComponent(AddEmployee_radioFemale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AddEmployee_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AddEmployee_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AddEmployee_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AddEmployee_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AddEmployee_loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AddEmployee_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AddEmployee_contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AddEmployee_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = AddEmployee_empName.getText();
        String position = AddEmployee_position.getSelectedItem().toString();
        String department = AddEmployee_department.getSelectedItem().toString();
        double salary = Double.parseDouble(AddEmployee_salary.getText());
        int age = Integer.parseInt(AddEmployee_age.getText());
        String password = AddEmployee_loginPassword.getText();
        String confirmPassword = AddEmployee_confirmPassword.getText();
        String phone = AddEmployee_contactNo.getText();
        String email = AddEmployee_email.getText();
        char gender;
        if(AddEmployee_radioMale.isSelected()) {
            gender = 'M';
        } else {
            gender = 'F';
        }
        //JOptionPane.showMessageDialog(null, "Position: "+position+" Department: "+department+" Gender: "+gender);
        String sql = "insert into employee(Name,Gender,Position,Department,Salary,Age,Password,ContactNo,Email) values(?,?,?,?,?,?,?,?,?)";
        String sql1 = "select SSN from employee where Email=?";
        String sql2 = "insert into login(SSN,Password) values(?,?)";
        int ssn;
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1,name);
            stmt.setString(2, String.valueOf(gender));
            stmt.setString(3,position);
            stmt.setString(4,department);
            stmt.setDouble(5, salary);
            stmt.setInt(6, age);
            stmt.setString(7, password);
            stmt.setString(8, phone);
            stmt.setString(9, email);
            int rows = stmt.executeUpdate();
            if(rows > 0) {
                stmt = con.prepareStatement(sql1);
                stmt.setString(1, email);
                rset = stmt.executeQuery();
                while(rset.next()) {
                    ssn = rset.getInt("SSN");
                    stmt = con.prepareStatement(sql2);
                    stmt.setInt(1, ssn);
                    stmt.setString(2, password);
                    rows = stmt.executeUpdate();
                }
                JOptionPane.showMessageDialog(null,"Successfully Added The Employee!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddEmployee_age;
    private javax.swing.JPasswordField AddEmployee_confirmPassword;
    private javax.swing.JTextField AddEmployee_contactNo;
    private javax.swing.JComboBox<String> AddEmployee_department;
    private javax.swing.JTextField AddEmployee_email;
    private javax.swing.JTextField AddEmployee_empName;
    private javax.swing.JPasswordField AddEmployee_loginPassword;
    private javax.swing.JComboBox<String> AddEmployee_position;
    private javax.swing.JRadioButton AddEmployee_radioFemale;
    private javax.swing.JRadioButton AddEmployee_radioMale;
    private javax.swing.JTextField AddEmployee_salary;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
